export interface SkillPack {
  id: string;
  name: string;
  badge: string;
  description: string;
  targetAudience: string;
  skillIds: string[];
  recommendedRole: string;
}

export const GENERAL_PURPOSE_SKILL_PACKS: SkillPack[] = [
  {
    id: 'pack-chief-of-staff',
    name: 'Executive Chief of Staff Pack',
    badge: 'Executive',
    description: 'High-leverage executive management: inbox triage, strategic meeting briefings, calendar protection, executive memo synthesis, and proactive cross-app task delegation.',
    targetAudience: 'Founders, C-Suite, Executives & Project Directors',
    skillIds: [
      'workspace-docs-architect',
      'workspace-calendar-strategist',
      'workspace-gmail-intelligence',
      'workspace-tasks-commander',
      'workspace-keep-notes',
      'direct-call-briefing-and-dialer',
      'whatsapp-omnichannel-communicator',
      'meta-context-subtraction',
      'meta-inbox-sweeper-tasks',
      'meta-blindspot-director',
      'meta-multi-skill-orchestrator',
    ],
    recommendedRole: 'FOUNDER / EXECUTIVE',
  },
  {
    id: 'pack-founder-startup',
    name: 'Business Founder & Startup Operations Pack',
    badge: 'Founder & Setup',
    description: 'Zero-to-one company incorporation, GST/compliance checklists, vendor RFP negotiation, 1-tap WhatsApp client messaging, pre-call pitch briefings, and financial cashflow modeling.',
    targetAudience: 'Entrepreneurs, Business Owners, Solopreneurs & Startup Founders',
    skillIds: [
      'business-entity-and-compliance-setup',
      'vendor-procurement-and-rfq-matcher',
      'b2b-customer-outreach-engine',
      'whatsapp-omnichannel-communicator',
      'direct-call-briefing-and-dialer',
      'workspace-sheets-modeler',
      'workspace-slides-designer',
      'workspace-docs-architect',
      'workspace-tasks-commander',
      'meta-outcome-roadmap',
    ],
    recommendedRole: 'BUSINESS OWNER / FOUNDER',
  },
  {
    id: 'pack-corporate-climber',
    name: 'Salaried Professional & Corporate Climber Pack',
    badge: 'Corporate Climber',
    description: 'Designed for high-performing salaried professionals: appraisal brag sheets in Docs, promotion scripts, skip-level 1-on-1 agendas, 5-slide executive decks, and high-impact workplace visibility.',
    targetAudience: 'Salaried Corporate Climbers, Engineering Leads, Product Managers & Mid/Senior Managers',
    skillIds: [
      'salaried-career-growth-and-appraisal-maximizer',
      'direct-call-briefing-and-dialer',
      'workspace-docs-architect',
      'workspace-slides-designer',
      'workspace-calendar-strategist',
      'workspace-tasks-commander',
      'meta-outcome-roadmap',
      'meta-blindspot-director',
      'meta-deep-research',
    ],
    recommendedRole: 'SALARIED CORPORATE / MANAGER',
  },
  {
    id: 'pack-sales-outreach',
    name: 'Customer Connect, Sales & WhatsApp Outreach Pack',
    badge: 'Sales & Outreach',
    description: 'High-converting multi-touch customer pipeline engine: 1-tap WhatsApp message generation, direct call dialer with pre-call briefings, Gmail pitch staging, and Google Sheets CRM tracker.',
    targetAudience: 'Sales Executives, Business Developers, Account Managers & Growth Leaders',
    skillIds: [
      'b2b-customer-outreach-engine',
      'whatsapp-omnichannel-communicator',
      'direct-call-briefing-and-dialer',
      'workspace-gmail-intelligence',
      'workspace-sheets-modeler',
      'workspace-docs-architect',
      'meta-context-subtraction',
    ],
    recommendedRole: 'SALES / BD / OUTREACH',
  },
  {
    id: 'pack-operations-procurement',
    name: 'Operations, Vendor Procurement & Finance Pack',
    badge: 'Operations',
    description: 'Vendor discovery, side-by-side cost & deliverable comparison matrices in Google Sheets, RFQ negotiation scripts, payment follow-up via WhatsApp, and automated spreadsheet formulas.',
    targetAudience: 'COOs, Operations Managers, Procurement Leads & Finance Heads',
    skillIds: [
      'vendor-procurement-and-rfq-matcher',
      'whatsapp-omnichannel-communicator',
      'workspace-sheets-modeler',
      'workspace-forms-creator',
      'workspace-tasks-commander',
      'meta-outcome-roadmap',
      'meta-html-ui-designer',
    ],
    recommendedRole: 'OPERATIONS / PROCUREMENT',
  },
  {
    id: 'pack-career-os',
    name: 'Life OS Career & Executive Talent Pack',
    badge: 'Career OS',
    description: 'Autonomous career counseling, job sourcing, proof-of-work collateral studio, and compensation engineering suite. Strictly read-only with human-in-the-loop staging.',
    targetAudience: 'Job Seekers, Executives in Transition, Career Pivoters & Senior Leaders',
    skillIds: [
      'candidate-aspiration-and-criteria-inquisitor',
      'career-trajectory-and-pivot-architect',
      'upskilling-and-skill-arbitrage-curator',
      'portal-profile-synthesizer-and-seo-optimizer',
      'ats-resume-and-impact-bullet-synthesizer',
      'multi-variant-static-portfolio-deployer',
      'bespoke-work-sample-and-proof-of-work-architect',
      'multi-board-job-scout-and-matchmaker',
      'circle-of-trust-and-referral-mobilizer',
      'network-infiltrator-and-referral-closer',
      'reverse-recruiter-and-talent-agent-desk',
      'stealth-diligence-and-backchannel-auditor',
      'interview-simulator-and-debrief-coach',
      'hike-maximization-and-offer-arbitrage-tactician',
      'compensation-and-offer-negotiation-desk',
      'job-campaign-pipeline-and-cadence-tracker',
      'resignation-and-onboarding-transition-navigator',
      'tailored-outreach-and-pitch-copywriter',
      'stealth-application-and-read-only-safety-gate',
    ],
    recommendedRole: 'ALL JOB SEEKERS / CAREER PIVOTERS',
  },
  {
    id: 'pack-deep-research',
    name: 'Deep Research & Market Intel Pack',
    badge: 'Intelligence',
    description: 'Empirical research and data synthesis: real-time web verification, competitor benchmarking, source-cited research dossiers, and executive notebooks.',
    targetAudience: 'Researchers, Strategists, Analysts & Consultants',
    skillIds: [
      'workspace-docs-architect',
      'workspace-sheets-modeler',
      'workspace-gemini-notebooks',
      'meta-deep-research',
      'meta-multi-skill-orchestrator',
    ],
    recommendedRole: 'RESEARCH / STRATEGY',
  },
  {
    id: 'pack-personal-life-os',
    name: 'Personal Life OS & Health Longevity Pack',
    badge: 'Life OS',
    description: 'Personal health checkup blueprints, aging parent care logs, domestic asset maintenance, grocery & packing checklists in Keep, daily habits, and household financial budgeting.',
    targetAudience: 'Individuals, Working Parents, Family Caregivers & Health Optimizers',
    skillIds: [
      'annual-preventive-health-blueprint',
      'workspace-keep-notes',
      'workspace-calendar-strategist',
      'workspace-tasks-commander',
      'workspace-drive-librarian',
      'meta-inbox-sweeper-tasks',
      'meta-outcome-roadmap',
    ],
    recommendedRole: 'EVERYONE / PERSONAL LIFE',
  },
  {
    id: 'pack-student-mastery',
    name: 'Student & Competitive Exam Mastery Pack',
    badge: 'Student',
    description: 'Feynman conceptual breakdowns, textbook syntheses, mock error diagnostic ledgers, and spaced-repetition revision schedules in Calendar & Tasks.',
    targetAudience: 'School Students, Competitive Exam Aspirants (UPSC, JEE, NEET, GRE, CAT) & University Students',
    skillIds: [
      'student-concept-synthesizer',
      'student-exam-strategy-and-mock-analyzer',
      'workspace-docs-architect',
      'workspace-gemini-notebooks',
      'workspace-calendar-strategist',
      'workspace-tasks-commander',
      'workspace-keep-notes',
    ],
    recommendedRole: 'STUDENT',
  },
  {
    id: 'pack-self-employed-practice',
    name: 'Self-Employed & Professional Practice Pack',
    badge: 'Self-Employed',
    description: 'Stock trader trade journaling & risk capital ledger, client desk retainer drafting, statutory filing reminders, and 1-tap WhatsApp client updates.',
    targetAudience: 'Stock Traders, CAs, Lawyers, Doctors, Architects & Independent Consultants',
    skillIds: [
      'stock-trader-journal-and-risk-ledger',
      'professional-services-client-desk',
      'whatsapp-omnichannel-communicator',
      'direct-call-briefing-and-dialer',
      'workspace-sheets-modeler',
      'workspace-docs-architect',
      'workspace-calendar-strategist',
      'workspace-tasks-commander',
    ],
    recommendedRole: 'SELF-EMPLOYED PROFESSIONAL',
  },
  {
    id: 'pack-entrepreneur-franchise',
    name: 'Entrepreneur & Franchise Business Owner Pack',
    badge: 'Entrepreneur',
    description: 'Pre-school/daycare operations, fee reconciliations in Sheets, parent broadcast drafts, entity incorporation, vendor RFQ negotiations, and multi-channel customer outreach.',
    targetAudience: 'Pre-School Owners, Franchise Operators, D2C Founders, Retail Store Owners & Agency Founders',
    skillIds: [
      'preschool-and-franchise-operations',
      'business-entity-and-compliance-setup',
      'vendor-procurement-and-rfq-matcher',
      'b2b-customer-outreach-engine',
      'whatsapp-omnichannel-communicator',
      'direct-call-briefing-and-dialer',
      'workspace-sheets-modeler',
      'workspace-tasks-commander',
    ],
    recommendedRole: 'ENTREPRENEUR / FOUNDER',
  },
  {
    id: 'pack-freelancer-creator',
    name: 'Freelancer & Creator Economy Pack',
    badge: 'Freelancer & Creator',
    description: 'Content creator script development, YouTube/Insta hooks, brand sponsorship pitch decks in Google Slides, rate card negotiation briefs, and lead outreach.',
    targetAudience: 'Content Creators, UI/UX Designers, Copywriters, Freelance Developers & Independent Consultants',
    skillIds: [
      'content-creator-growth-and-sponsorship-engine',
      'b2b-customer-outreach-engine',
      'whatsapp-omnichannel-communicator',
      'direct-call-briefing-and-dialer',
      'workspace-docs-architect',
      'workspace-slides-designer',
      'workspace-sheets-modeler',
      'workspace-tasks-commander',
    ],
    recommendedRole: 'FREELANCER / CREATOR',
  },
  {
    id: 'pack-senior-vitality',
    name: 'Senior Vitality & Peaceful Care Pack',
    badge: 'Senior Care',
    description: 'Ultra-simple, zero-confusion layout for prescription medicine reminders, doctor appointment scheduling, daily walk routines, and 1-tap WhatsApp family check-ins.',
    targetAudience: 'Retired Seniors & Family Eldercare Support',
    skillIds: [
      'senior-vitality-and-medication-guardian',
      'workspace-calendar-strategist',
      'workspace-keep-notes',
      'whatsapp-omnichannel-communicator',
    ],
    recommendedRole: 'SENIOR',
  },
  {
    id: 'pack-admin-sentinel',
    name: 'Platform Admin & System Auto-Healer Pack',
    badge: 'Admin Sentinel',
    description: 'Real-time API error monitoring, automated bug diagnostics and self-healing recommendations, tenant governance, skill pack allocations, and executive business strategy modeling.',
    targetAudience: 'Platform Administrators, Executive Leadership & DevOps Sentinels',
    skillIds: [
      'admin-system-auto-healer',
      'admin-business-strategist-and-market-intel',
      'admin-user-and-org-governance',
      'workspace-docs-architect',
      'workspace-sheets-modeler',
      'workspace-slides-designer',
    ],
    recommendedRole: 'ADMIN',
  },
];
