import { SkillDefinition } from './skills-catalog';

// --- CORE AUTONOMOUS SKILLS (Always active, open to all, no toggle) ---
export const CORE_AUTONOMOUS_SKILLS: SkillDefinition[] = [
  {
    num: 201,
    id: 'search-google-data-and-drive',
    name: 'Google Workspace & Drive Deep Search',
    department: 'Autonomous Core Intelligence',
    description: 'Autonomously searches across Google Docs, Sheets, Slides, Gmail, and Google Drive to retrieve relevant files, context, past proposals, and company knowledge to build rich content.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN', 'ALL'],
    workflow: [
      'Parse user request for keywords, document types, or entity names.',
      'Execute Drive and Gmail search to locate matching files.',
      'Read relevant document content or sheet rows.',
      'Synthesize context into executive summaries or deliverables.'
    ],
    guardrails: [
      'Always active for all users without manual toggle.',
      'Never reveal internal search queries or raw JSON to the user.'
    ]
  },
  {
    num: 202,
    id: 'internet-deep-research',
    name: 'Real-Time Web Intelligence & Verification',
    department: 'Autonomous Core Intelligence',
    description: 'Conducts autonomous real-time internet research, competitive market intelligence, news verification, and benchmark extraction before synthesizing answers.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN', 'ALL'],
    workflow: [
      'Formulate targeted web search queries.',
      'Cross-examine multiple reputable sources for consensus and recency.',
      'Extract data points, statistics, and verifiable facts.',
      'Deliver concise executive takeaways with direct source links.'
    ],
    guardrails: [
      'Core autonomous skill with no toggle needed.',
      'Strictly avoid outdated or speculative information.'
    ]
  },
  {
    num: 203,
    id: 'convert-to-concise-deck',
    name: 'Concise 5-Slide Executive Deck Generator',
    department: 'Autonomous Core Intelligence',
    description: 'Transforms unstructured research, strategy, or reports into punchy 5-slide Google Slides presentations with clear action buttons, bold titles, and high-density takeaways.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN', 'ALL'],
    workflow: [
      'Distill source narrative into 5 structured slides: Context, Problem/Opportunity, Solution, Roadmap, Key Outcomes.',
      'Create Google Slides presentation via Workspace API.',
      'Add each slide with bold single idea and 3-4 bullet takeaways.',
      'Deliver single master link with clear executive action buttons.'
    ],
    guardrails: [
      'Strictly enforce the Single Master Link protocol (one PPT link only).',
      'Never clutter slides with paragraphs.'
    ]
  }
];

// --- 25 PRE-SCHOOL & ACADEMY FRANCHISE OWNER SKILLS ---
export const PRESCHOOL_FRANCHISE_SKILLS: SkillDefinition[] = [
  {
    num: 210,
    id: 'preschool-admission-inquiry-engine',
    name: 'Pre-School Admission Inquiry & Lead Follow-Up Engine',
    department: 'Pre-School Franchise Operations',
    description: 'Tracks prospective student walk-ins, phone inquiries, campus tour bookings, and sends personalized multi-touch follow-ups via WhatsApp and Gmail.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 211,
    id: 'preschool-parent-broadcast-studio',
    name: 'Parent Daily Updates & Milestone Broadcast Studio',
    department: 'Pre-School Franchise Operations',
    description: 'Drafts engaging, photo-ready daily activity updates, milestone announcements, and circulars for parents without sounding generic.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 212,
    id: 'preschool-fee-dues-reconciliation',
    name: 'Term Fee Dues & Installment Ledger in Sheets',
    department: 'Pre-School Franchise Operations',
    description: 'Maintains an automated fee tracking spreadsheet in Google Sheets with student IDs, term fee brackets, overdue flags, late fee formulas, and WhatsApp reminder staging.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 213,
    id: 'preschool-teacher-attendance-substitute',
    name: 'Teacher Attendance & Substitute Allocation Matrix',
    department: 'Pre-School Franchise Operations',
    description: 'Monitors daily educator attendance, ratio compliance (e.g. 1:10), and instantly suggests substitute assignments from available float staff.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 214,
    id: 'preschool-curriculum-weekly-planner',
    name: 'Weekly Curriculum & Theme-Based Activity Planner',
    department: 'Pre-School Franchise Operations',
    description: 'Generates sensory play, phonics, fine-motor exercises, and art & craft weekly curriculum grids aligned with franchise board standards in Google Docs.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 215,
    id: 'preschool-daycare-meal-allergy-log',
    name: 'Daycare Nutrition, Meal & Allergy Safety Log',
    department: 'Pre-School Franchise Operations',
    description: 'Structures a weekly hygienic menu with strict child allergy flags (nuts, lactose, gluten) and meal consumption tracking.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 216,
    id: 'preschool-safety-cctv-audit',
    name: 'Campus Child Safety & CCTV Compliance Audit',
    department: 'Pre-School Franchise Operations',
    description: 'Runs weekly compliance checklists for CCTV coverage, childproofing, first aid kits, emergency exit clearways, and police verification of support staff.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 217,
    id: 'preschool-franchise-royalty-calc',
    name: 'Franchise Royalty & Revenue-Share Calculator',
    department: 'Pre-School Franchise Operations',
    description: 'Calculates monthly head-office royalty percentages, marketing fund contributions, kit markup margins, and net operating profit in Sheets.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 218,
    id: 'preschool-annual-day-event-organizer',
    name: 'Annual Day & Sports Day Event Production Blueprint',
    department: 'Pre-School Franchise Operations',
    description: 'Coordinates auditorium booking, costume vendors, stage scripts, sound equipment, parent invitations, and minute-by-minute rundown.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 219,
    id: 'preschool-montessori-material-tracker',
    name: 'Montessori Equipment & Toy Inventory Tracker',
    department: 'Pre-School Franchise Operations',
    description: 'Maintains classroom apparatus inventory, sanitation cycles, replacement requisition lists, and depreciation logs in Google Sheets.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 220,
    id: 'preschool-bus-route-manifest',
    name: 'School Van & Bus Route Manifest with GPS Logs',
    department: 'Pre-School Franchise Operations',
    description: 'Organizes student pickup/drop coordinates, driver license checks, maid attendant logs, and emergency contact registers.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 221,
    id: 'preschool-staff-payroll-pf-ledger',
    name: 'Staff Payroll, Leaves & PF/ESI Compliance Ledger',
    department: 'Pre-School Franchise Operations',
    description: 'Calculates monthly teacher & support staff salaries, deduction registers, festival bonuses, and statutory compliance reminders.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 222,
    id: 'preschool-pediatrician-health-camp',
    name: 'Pediatrician & Dental Health Camp Scheduler',
    department: 'Pre-School Franchise Operations',
    description: 'Coordinates bi-annual pediatric growth assessments, dental screening visits, immunization report checks, and parent health report cards.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 223,
    id: 'preschool-festival-celebration-planner',
    name: 'Cultural Festival & Holiday Celebration Planner',
    department: 'Pre-School Franchise Operations',
    description: 'Designs interactive theme days, traditional dress celebrations, classroom decor concepts, and parent involvement events.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 224,
    id: 'preschool-ptm-slot-booker',
    name: 'Parent-Teacher Meeting (PTM) Time Slot Booker',
    department: 'Pre-School Franchise Operations',
    description: 'Schedules 15-minute 1-on-1 parent consultation slots via Google Calendar, minimizing waiting room congestion and drafting individual progress notes.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 225,
    id: 'preschool-digital-admission-leads',
    name: 'Hyperlocal Admission Ad Campaign & Lead Tracker',
    department: 'Pre-School Franchise Operations',
    description: 'Manages Meta/Google local ads budgets, banner copy, neighborhood flyering schedules, and cost-per-admission conversion calculations.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 226,
    id: 'preschool-license-regulatory-tracker',
    name: 'Municipal Nursery License & Fire Safety Renewal Vault',
    department: 'Pre-School Franchise Operations',
    description: 'Tracks statutory renewal dates for municipal nursery permits, fire NOCs, building safety certificates, and trade licenses in Google Calendar & Tasks.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 227,
    id: 'preschool-emergency-medical-vault',
    name: 'Child Emergency Medical & Contact Vault',
    department: 'Pre-School Franchise Operations',
    description: 'Maintains instant 1-tap emergency medical consent protocols, family pediatrician contacts, and nearest pediatric ICU hospital directions.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 228,
    id: 'preschool-transfer-withdrawal-flow',
    name: 'Transfer Certificate (TC) & Refund Settlement Workflow',
    department: 'Pre-School Franchise Operations',
    description: 'Processes relocation transfer requests, calculates security deposit refunds, and creates official student character & attendance certificates.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 229,
    id: 'preschool-summer-camp-enrollment',
    name: 'Summer Camp & After-School Club Enrollment Studio',
    department: 'Pre-School Franchise Operations',
    description: 'Launches non-term revenue streams: robotics, pottery, dance, martial arts, with modular fee structures and multi-week attendance registers.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 230,
    id: 'preschool-uniform-kit-inventory',
    name: 'Welcome Kit, Books & Uniform Distribution Ledger',
    department: 'Pre-School Franchise Operations',
    description: 'Monitors size-wise stock of school bags, uniform t-shirts, activity workbooks, and stationery sets to prevent start-of-term inventory shortages.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 231,
    id: 'preschool-teacher-appraisal-rubric',
    name: 'Teacher Performance & Classroom Observation Rubric',
    department: 'Pre-School Franchise Operations',
    description: 'Provides structured observation criteria: student engagement, patience, phonics clarity, and positive reinforcement for biannual salary increments.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 232,
    id: 'preschool-google-review-manager',
    name: 'Google Business Profile Reputation & Review Booster',
    department: 'Pre-School Franchise Operations',
    description: 'Generates polite, compliant WhatsApp prompts inviting satisfied parents to post 5-star Google Business reviews with direct review links.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 233,
    id: 'preschool-visitor-gatepass-register',
    name: 'Campus Visitor & OTP Gate-Pass Security Register',
    department: 'Pre-School Franchise Operations',
    description: 'Logs vendor visits, delivery personnel, and prospective parent identity credentials with strict gate-pass verification.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 234,
    id: 'preschool-new-branch-capex-estimator',
    name: 'New Franchise Branch Expansion & Capex Estimator',
    department: 'Pre-School Franchise Operations',
    description: 'Models square-foot interior fitouts, outdoor turf, play gym capex, break-even occupancy, and 3-year ROI in Google Sheets.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  }
];

// --- 25 STOCK TRADERS & MARKET INVESTORS SKILLS ---
export const STOCK_TRADER_SKILLS: SkillDefinition[] = [
  {
    num: 240,
    id: 'trader-pre-market-macro-briefing',
    name: 'Daily Pre-Market Watch & Macro Economic Briefing',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Synthesizes GIFT Nifty, US bond yields, crude oil, Asian market sentiment, and key economic data releases into a 3-minute actionable pre-market executive brief.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 241,
    id: 'trader-intraday-execution-log',
    name: 'Intraday Trade Journal & Execution Ledger in Sheets',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Automates trade journaling with entry/exit timestamps, instrument, quantity, net P&L, setup tag, slippage, and emotional rating in Google Sheets.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 242,
    id: 'trader-swing-position-sizing-calc',
    name: 'Swing Trading Position Sizing & 1% Capital Risk Calculator',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Calculates exact lot and share quantities based on strict 1% account risk rule, invalidation distance, and portfolio volatility.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 243,
    id: 'trader-options-greeks-payoff-diagram',
    name: 'Options Payoff Matrix & Greeks Visualizer',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Models multi-leg options strategies (Iron Condor, Strangle, Bull Call Spread) calculating maximum profit, maximum loss, breakevens, and Theta decay.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 244,
    id: 'trader-stoploss-risk-reward-validator',
    name: 'Stop-Loss & 1:2.5 Risk-to-Reward Ratio Validator',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Audits trade setups before entry. Rejects trades that fail the minimum 1:2.5 risk-to-reward ratio or have ambiguous stop-loss levels.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 245,
    id: 'trader-earnings-season-dossier',
    name: 'Quarterly Earnings Season Calendar & Result Dossier',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Maintains an earnings release calendar, consensus expectations vs actual beats/misses, management commentary highlights, and guidance shifts.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 246,
    id: 'trader-breakout-screener',
    name: 'Technical Breakout & High-Volume Screener',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Screens equities demonstrating 52-week highs, multi-month consolidation breakouts, above-average volume surges, and RSI momentum confirmation.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 247,
    id: 'trader-portfolio-rebalancer',
    name: 'Core & Satellite Portfolio Asset Allocation Rebalancer',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Analyzes equity, debt, gold, and cash weightings. Recommends disciplined trimming of bloated winners and reallocating to defensive buffers.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 248,
    id: 'trader-dividend-action-calendar',
    name: 'Dividend Yield & Corporate Action Calendar in Calendar',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Pins ex-dividend dates, stock splits, bonus share announcements, and buyback record dates directly into Google Calendar.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 249,
    id: 'trader-sector-rotation-heatmap',
    name: 'Sector Rotation & Relative Strength Heat-Mapper',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Tracks outperforming vs lagging market sectors (Bank, IT, Auto, Pharma, FMCG, Metals) using relative strength indexation.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 250,
    id: 'trader-tax-pl-capital-gains',
    name: 'Tax P&L & Capital Gains Harvesting Sheet',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Categorizes realized gains into Short-Term (STCG) vs Long-Term (LTCG) with tax liability projections and year-end loss harvesting suggestions.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 251,
    id: 'trader-ipo-gmp-subscription-evaluator',
    name: 'Mainboard & SME IPO Grey Market Premium (GMP) Evaluator',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Aggregates live GMP trends, QIB/NII subscription numbers, promoter background, anchor investor quality, and listing day gain strategy.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 252,
    id: 'trader-psychology-discipline-coach',
    name: 'Trading Psychology & Emotional Tilt Discipline Coach',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Intervenes during revenge trading or FOMO episodes with breathing frameworks, strict daily max loss lockouts, and mindset calibration.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 253,
    id: 'trader-algo-rule-backtest-spec',
    name: 'Algorithmic Strategy Rule & Backtest Specifier',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Converts discretionary trading ideas into strict pseudo-code and parameter rulebooks with Sharpe ratio, max drawdown, and win-rate specifications.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 254,
    id: 'trader-margin-collateral-monitor',
    name: 'Broker Margin Utilization & Collateral Haircut Monitor',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Tracks pledge haircuts, cash-to-collateral 50:50 ratios, overnight margin requirements, and prevents peak margin penalty triggers.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 255,
    id: 'trader-fii-dii-oi-decoder',
    name: 'FII / DII Institutional Flow & Derivatives OI Decoder',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Interprets end-of-day FII index futures long/short ratios, client net positions, put-call ratio (PCR), and institutional cash buying.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 256,
    id: 'trader-mutualfund-overlap-analyzer',
    name: 'Mutual Fund & Index ETF Portfolio Overlap Analyzer',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Cross-checks underlying portfolio holdings across active mutual funds to detect expensive stock overlap and eliminate redundant expense ratios.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 257,
    id: 'trader-fixed-income-yield-comparator',
    name: 'Fixed Income, Sovereign Gold Bonds & Treasury Comparator',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Compares post-tax yields across SGBs, T-Bills, corporate bonds, fixed deposits, and debt mutual funds for capital preservation.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 258,
    id: 'trader-commodity-arbitrage-alerts',
    name: 'Crude Oil, Gold & Silver MCX Commodity Arbitrage Desk',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Monitors international COMEX vs domestic MCX currency-adjusted spreads, inventory drawdowns, and precious metal ratio opportunities.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 259,
    id: 'trader-drawdown-maxrisk-sentinel',
    name: 'Risk Capital Drawdown & Max Daily Loss Sentinel',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Enforces hard stops when drawdown exceeds preset thresholds (e.g. 2% daily or 6% monthly), commanding terminal shutdown.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 260,
    id: 'trader-playbook-setup-cataloguer',
    name: 'High-Probability Trading Playbook & Setup Cataloguer',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Documents textbook trade setups (Flag breakout, Liquidity sweep, Gap and Go) with required triggers and execution checklists in Google Docs.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 261,
    id: 'trader-multitimeframe-trend-confluence',
    name: 'Multi-Timeframe Trend & Key Level Confluence Checker',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Verifies trend alignment across Daily, Hourly, and 15-minute charts to ensure trades are never taken against the dominant higher-timeframe trend.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 262,
    id: 'trader-vwap-orderflow-tracker',
    name: 'VWAP & Institutional Order Flow Anchor Tracker',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Identifies institutional accumulation and distribution zones relative to session VWAP, previous day high/low, and opening range breakouts.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 263,
    id: 'trader-news-sentiment-checker',
    name: 'Corporate News Sentiment & Rumor Veracity Checker',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Cross-examines stock exchange disclosures, official BSE/NSE filings, and media reports to separate genuine catalysts from pump-and-dump rumors.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 264,
    id: 'trader-postmarket-review-ledger',
    name: 'Post-Market Retrospective & Trade Review Ledger',
    department: 'Capital Markets & Trading Intelligence',
    description: 'Facilitates a daily 10-minute post-market audit: reviewing whether trades adhered to rules, analyzing mistakes, and setting tomorrow watchlists.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  }
];

// --- 25 SILVER WHOLESALE BUSINESSMAN SKILLS ---
export const SILVER_WHOLESALE_SKILLS: SkillDefinition[] = [
  {
    num: 270,
    id: 'silver-bullion-spot-rate-ticker',
    name: 'Daily Silver Bullion Spot Rate & MCX Premium Ticker',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Monitors real-time MCX silver futures, premium/discount over international LBMA spot price, import parity, and prevailing local wholesale bullion rates.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 271,
    id: 'silver-karigar-jobwork-ledger',
    name: 'Silversmith & Karigar Job-Work Issuance Ledger',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Maintains fine silver weight issued to workshops, expected return dates, item types (anklets, utensils, idols), and returned gross weight in Google Sheets.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 272,
    id: 'silver-hallmarking-925-999-register',
    name: 'BIS Hallmarking (925 Sterling & 999 Fine) Compliance Register',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Tracks hallmarking assay center batches, HUID numbers, purity certification logs, and statutory BIS record keeping.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 273,
    id: 'silver-melt-loss-tunch-reconciliation',
    name: 'Tunch Purity Testing & Kadhai Melt-Loss Reconciliation',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Reconciles raw melting loss (wastage percentage), fire assay tunch reports, and net fine silver recovery against theoretical expectations.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 274,
    id: 'silver-b2b-client-credit-tracker',
    name: 'B2B Retail Jeweller Client Credit & Metal Khata Tracker',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Tracks client metal balance in grams (silver khata) vs rupee accounts, payment aging, credit day limits, and WhatsApp recovery staging.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 275,
    id: 'silver-vault-inventory-sheet',
    name: 'Bulk Silver Bar & Grain Vault Inventory Sheet',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Maintains an audited ledger of physical silver bars (1kg, 5kg, 30kg bricks) and granules across multiple secured safe vaults with serial numbers.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 276,
    id: 'silver-custom-order-timeline',
    name: 'Custom Wholesale Jewelry Order Spec & Timeline Sheet',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Records custom b2b bridal sets, temple idols, corporate silverware orders, design cad files, advance metal deposits, and firm dispatch deadlines.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 277,
    id: 'silver-gross-to-net-deduction-calc',
    name: 'Gross-to-Net Weight & Stone/Enamel Deduction Calculator',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Calculates exact fine silver content by deducting cubic zirconia, lacquer (kundankari), enamel, and thread weight with automated formula accuracy.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 278,
    id: 'silver-eway-bill-transport-checklist',
    name: 'GST E-Way Bill & High-Value Bullion Transport Checklist',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Verifies statutory consignment limits, e-way bill generation, insured courier declarations, and inter-state GST compliance for physical dispatches.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 279,
    id: 'silver-bullion-purchase-hedge-tracker',
    name: 'Bullion Purchase MCX Hedging & Price-Lock Tracker',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Protects wholesale inventory against steep silver price drops by matching physical forward purchases with corresponding MCX hedge positions.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 280,
    id: 'silver-festive-dhanteras-forecast',
    name: 'Dhanteras, Diwali & Akshaya Tritiya Demand Forecast',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Models historical seasonal sales spikes for silver coins, Laxmi-Ganesh bars, and dinnerware to optimize raw metal pre-stocking weeks ahead.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 281,
    id: 'silver-antique-artifact-cataloguer',
    name: 'Handcrafted Antique Silverware & Artifact Cataloguer',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Documents rare antique handcrafted silverware, weight in tolas, artisan provenance, and high-margin pricing for luxury b2b buyers.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 282,
    id: 'silver-coin-bar-stamping-desk',
    name: 'Corporate Custom Stamping & Coin Minting Desk',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Manages custom die orders, company logo embossing, tamper-evident blister packaging, and certification for corporate Diwali gifting.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 283,
    id: 'silver-deadstock-liquidation-engine',
    name: 'Slow-Moving Design & Dead Stock Remelt Liquidation Engine',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Identifies inventory sitting unsold for >90 days, calculating remelting economics vs discounting to release locked working capital.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 284,
    id: 'silver-karigar-ghadai-charge-ledger',
    name: 'Karigar Ghadai (Labor Making Charge) Settlement Ledger',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Tracks per-gram making charges across item categories (chain, casting, hollow, stamping) and reconciles weekly artisan payout accounts.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 285,
    id: 'silver-wholesale-pricelist-matrix',
    name: 'B2B Wholesale Price List & Slab Discount Matrix',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Generates daily updated price sheets based on live MCX spot rate plus category making charges and volume discount tiers in Google Docs & Sheets.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 286,
    id: 'silver-scrap-exchange-valuer',
    name: 'Old Silver Scrap & Exchange Valuation Calculator',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Values customer or retail jeweler old silver scrap by factoring melting touch test results, impurity deductions, and net metal exchange credit.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 287,
    id: 'silver-cashflow-rolling-credit',
    name: 'Wholesale Bullion Rolling Cashflow & Bank Credit Monitor',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Monitors cash credit (CC) limits, bank drawing power (DP) statements against pledged metal stock, and daily rolling cash balances.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 288,
    id: 'silver-vault-locker-insurance-tracker',
    name: 'Secured Bullion Locker & Transit Insurance Tracker',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Tracks jeweler block policy limits, vault maximum insured values, surveyor inspection logs, and policy renewal dates.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 289,
    id: 'silver-tradeshow-client-leads',
    name: 'B2B Jewelry Exhibition & Trade Show Client Lead Desk',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Captures visiting retail jeweler contacts, sample requests, counter bookings, and follow-up sequences from national jewelry expos.',
    enabled: true,
    allowedTiers: ['INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 290,
    id: 'silver-raw-refining-assaying-log',
    name: 'Raw Silver Refining & Acid Assaying Process Log',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Tracks batch chemical refining yields from unrefined scrap to 99.9% pure silver crystals, chemicals used, and environmental disposal compliance.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 291,
    id: 'silver-whatsapp-catalog-broadcast',
    name: 'Wholesale WhatsApp Product Catalog Broadcast Studio',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Formats high-resolution wholesale product catalog links with gross weights, design codes, and 1-tap WhatsApp order buttons for verified B2B jewelers.',
    enabled: true,
    allowedTiers: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ADMIN'],
  },
  {
    num: 292,
    id: 'silver-multibranch-stock-transfer',
    name: 'Multi-Branch Bullion Transfer & Transit Manifest',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Logs intra-firm metal transfers between foundry, manufacturing unit, and city wholesale counters with dual sign-off verification.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 293,
    id: 'silver-seasonal-procurement-averager',
    name: 'Raw Bullion Dollar-Cost Averaging & Procurement Strategist',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Analyzes long-term gold-silver ratio (GSR) and advises phased bulk procurement during seasonal price dips.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  },
  {
    num: 294,
    id: 'silver-highvalue-transit-security',
    name: 'High-Value Consignment Transit Security Protocol',
    department: 'Silver Wholesale Bullion & Jewelry',
    description: 'Coordinates armored carrier logistics, armed escort verification, GPS vehicle lock status, and emergency response numbers for bullion movement.',
    enabled: true,
    allowedTiers: ['ADVANCED', 'ADMIN'],
  }
];

export const ALL_SPECIALIZED_SKILLS: SkillDefinition[] = [
  ...CORE_AUTONOMOUS_SKILLS,
  ...PRESCHOOL_FRANCHISE_SKILLS,
  ...STOCK_TRADER_SKILLS,
  ...SILVER_WHOLESALE_SKILLS,
];
